apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name:
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:
subjects:
- kind: ServiceAccount
  name:
  namespace: default
